### ISSUE TITLE
DevBlocks

### ISSUE THREAD

**Issue by powerbox1000** [retro-person/Scratch-Archive#2]
# As the creator of DevBlocks
I highly recommend you use [this .zip file](https://github.com/powerbox1000/dev-blocks/archive/main.zip) instead.

**Comment by retro-person** [comment]
Ooh, thanks!

**Comment by retro-person** [comment]
Oh... One problem though... I can't upload files greater than 25 MB because of my free GitHub plan... Sorry. : (

**Comment by powerbox1000** [comment]
@retro-person  Use [github desktop](https://desktop.github.com) to do it; I use free plan and it works for me. Or see [my repo](https://github.com/powerbox1000/Scratch-Archive/tree/master/dev-blocks).

**Comment by retro-person** [comment]
Oh, thanks! Even though they _officially_ don't support Linux (I'm using a ChromeBook emulating Linux), I found someone who made a fork for Linux, so we'll see how well that goes.

**Comment by retro-person** [comment]
Nevermind... It says that, if I do this, I'll never be able to commit to this repository again! : (

**Comment by powerbox1000** [comment]
> Nevermind... It says that, if I do this, I'll never be able to commit to this repository again! : (

Then see [my repo](https://github.com/powerbox1000/Scratch-Archive/tree/master/dev-blocks).

**Comment by retro-person** [comment]
Hmm... I don't know what to do...

**Comment by powerbox1000** [comment]
Just download the 2 .zip files and upload them to _your_ repo. No need to credit me!

**Comment by retro-person** [comment]
Yes; I know! But it says it won't let me upload _any_ files of _any_ size after I do this! : (

**Comment by powerbox1000** [comment]
> Yes; I know! But it says it won't let me upload _any_ files of _any_ size after I do this! : (

I mean online.

**Comment by retro-person** [comment]
I am slightly confused... What do you mean by "online"?

**Comment by nreef** [comment]
> I am slightly confused... What do you mean by "online"?

I think he means on the GitHub website rather than GitHub Desktop.

**Comment by retro-person** [comment]
Oh! That might work.

**Comment by nreef** [comment]
Also, **how did you get the Desktop app for the ChromeOS Linux VM?** I'm probably not gonna use it because it's probably a little unstable but just wondering.

**Comment by retro-person** [comment]
Check [this](https://github.com/shiftkey/desktop) out.

**Comment by retro-person** [comment]
> Yes; I know! But it says it won't let me upload _any_ files of _any_ size after I do this! : (

Also, here's the error I get when I try to do this:
![Screenshot 2020-11-12 at 7 57 46 PM](https://user-images.githubusercontent.com/71155308/99014809-7b6fb900-2521-11eb-9343-c9d5e736357b.png)

**Comment by nreef** [comment]
Ok. Does it work uploading to web?

**Comment by retro-person** [comment]
Nope. It works when I push locally, but gives me this error when trying to push to remote.

**Comment by nreef** [comment]
Huh, ok... not too sure what's going on...

**Comment by retro-person** [comment]
:"( I'll now try pushing via the Linux terminal.

**Comment by nreef** [comment]
Do it through github.com, not the app.

**Comment by retro-person** [comment]
How? When I try to upload via the website, any file greater than _25_ MB gives me "Yowza, that's a big file. Try a different one, or try GitHub LFS [Large File Storage FYI.]". : (

**Comment by nreef** [comment]
Hmmmm... Is there by chance any way to shrink the file?

**Comment by retro-person** [comment]
Not really...

**Comment by retro-person** [comment]
Also, uploading via the Linux terminal doesn't work...

**Comment by nreef** [comment]
My last suggestion is try the [Git LFS](https://git-lfs.github.com/).

**Comment by retro-person** [comment]
Cool! I thought LFS was priced.

**Comment by nreef** [comment]
Me too. Apparently not!

**Comment by nreef** [comment]
Tell me if it works.

**Comment by retro-person** [comment]
Give me a sec...

**Comment by retro-person** [comment]
It takes a while : \

**Comment by nreef** [comment]
It's fine! I'll be working on my own repositories while I wait.

**Comment by retro-person** [comment]
*Especially if you're using a Linux VM for ChromeOS that's still in "Beta"! : P

**Comment by nreef** [comment]
Ha yep. The Linux VM (actually named Crostini) is pretty new, so it's buggy. I try to use Atom on it and it sometimes stops responding. Fun fact: I'm using Chrome in it right now!

**Comment by retro-person** [comment]
Sorry for the wait; I had a music lesson : P

**Comment by nreef** [comment]
Sure, totally fine! I was working on my own repositories (pages and stuff)

**Comment by retro-person** [comment]
Yep! Good news: After some fumbling around, it is now uploading! Give it a sec.

**Comment by nreef** [comment]
**Great!**

**Comment by retro-person** [comment]
It does seem slower now, though.

**Comment by nreef** [comment]
Huh ok...

**Comment by retro-person** [comment]
Noo!
![Screenshot 2020-11-12 at 9 05 47 PM](https://user-images.githubusercontent.com/71155308/99019682-db1e9200-252a-11eb-820f-e802019a318f.png)

**Comment by nreef** [comment]
Did you follow all the steps on the website?

**Comment by retro-person** [comment]
Yup... I'm trying a different way now; still using LFS.

**Comment by nreef** [comment]
OK

**Comment by retro-person** [comment]
Noo again! :"( And the only (overcomplicated) solution I can find is this:
![Screenshot 2020-11-12 at 9 10 35 PM](https://user-images.githubusercontent.com/71155308/99020026-ad861880-252b-11eb-93e9-12fe74efcaef.png)

**Comment by nreef** [comment]
Ok, sorry :cry:

**Comment by retro-person** [comment]
Any other ideas? :"(

**Comment by nreef** [comment]
Unfortunately, no. It's complicated, but maybe we could try that tomorrow? I really don't know.

**Comment by nreef** [comment]
I'm going to my friends house tomorrow and they have a Windows PC. If you share the files with me, I can maybe try on my end. Sound good @retro-person ?

**Comment by retro-person** [comment]
Sure! Sorry for the late response. I'm actually supposed to be sleeping right now X D

**Comment by nreef** [comment]
lol me too XD

well gtg

**Comment by retro-person** [comment]
Okay! It seems the zip file is now uploaded, so I will close this issue.
